# Generated by Django 3.1.5 on 2021-01-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resizedimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='resizedimage',
            name='width',
        ),
    ]
